### ISSUE TITLE
the template is not copied over

### ISSUE THREAD

**Issue by epijim** [insightsengineering/thevalidatoR#20]
When you run the gh-action, you get the error:

![image](https://user-images.githubusercontent.com/2760096/136838955-f59868da-ad63-4cbf-a34b-3378f9bab2de.png)

I think it might be because the line below puts into `/`. I can't remember exactly what I was doing, but I remember running `pwd` at one point, and pretty sure it was somewhere like `/workspace/` that was 'root' in terms of where you enter the container.
https://github.com/insightsengineering/thevalidatoR/blob/main/Dockerfile#L11

**Comment by epijim** [comment]
hmm this didn't work: reverting it back to the original

![image](https://user-images.githubusercontent.com/2760096/136843544-d53828fe-051e-435a-8188-bde92a80771a.png)

**Comment by dinakar29** [comment]
`/github/workspace/`, (aka [`$GITHUB_WORKSPACE`](https://docs.github.com/en/actions/learn-github-actions/environment-variables) || `${{ github.workspace }}`) is mounted at CI runtime during CI run either to the container or the VM, depending on where the workflow is being run and is not inherently part of the image being used (if the workflow is being run in a container).

I believe this can be solved by simply copying the template in the workhorse script for the action. Let me try that.

**Comment by dinakar29** [comment]
Resolved this: https://github.com/insightsengineering/rbmi/runs/3875207626

**Comment by epijim** [comment]
thanks!
