### ISSUE TITLE
Decouple execution environment from action, allowing for composition with r-lib/actions

### ISSUE THREAD

**Issue by dgkf-roche** [insightsengineering/thevalidatoR#29]
# Motivation

Execution environment is a key part of documenting package behaviors. There is no way we can create a singular environment that is representative of all use-cases. Base OS, system dependencies, R build, etc - all effect execution behaviors.

Likewise, if we want to be able to compose with `r-lib/actions`, we likely want to structure our action the same way. That is, the R installation is its own action, which composes as part of a workflow. Most similar to our action would be the [`R CMD check` action](https://github.com/r-lib/actions/blob/master/check-r-package/action.yaml), which makes use of the R installation configured in a previous action in which to run the checks.

# Options/Considerations

1. Clone scripts from the action repo as part of the action? This seems like a hack, but it would be the most straightforward.
2. Composite/shell action that embeds all steps within a `runs:steps:run:` script. 
3. (1) is a bit messy - we could spin up a separate R package to build the actual report such that the contents of the run step would only need to install the package and run a function from it. Shipping the code as an R package, especially one installed as a `github_remote`, is effectively a clone of the script files, but might be more palatable.

---

Any other suggestions/thoughts?

**Comment by dgkf-roche** [comment]
I think spinning off a separate package would be cleanest, and would allow us to manage action dependencies more easily as R package dependencies which might also clean up the setup.

**Comment by dinakar29** [comment]
We'll convert this to a `composite` action. The Docker-based action is definitely restrictive.

**Comment by dinakar29** [comment]
@dgkf-roche and @epijim:

@knightdave has graciously volunteered to convert this to a composite action. This will allow us to use any form of R to build the report (i.e. R on a container image, R on the VM, R on bare-metal etc).

**Comment by epijim** [comment]
This is fantastic @knightdave - thanks for taking this on.
