### ISSUE TITLE
Currently failing (see admiral)

### ISSUE THREAD

**Issue by epijim** [insightsengineering/thevalidatoR#53]
Admiral builds have: 

![image](https://user-images.githubusercontent.com/2760096/153705901-82bf87d1-6958-4ed0-9e18-49002303d44e.png)

Which corresponds to  https://github.com/insightsengineering/thevalidatoR/blob/main/template.Rmd#L151

<img width="652" alt="image" src="https://user-images.githubusercontent.com/2760096/153705925-3b5f00d9-7706-4971-95f1-79497d79955c.png">

**Comment by epijim** [comment]
It may be an admiral issue: https://github.com/pharmaverse/admiral/issues/918#issuecomment-1037091988

@dinakar29 - do we have tooling from IDR to do like pre-checks? e.g. in this case it would be cool to fail the report early if they have things in the DESCRIPTION that don't exist in terms of what 'CRAN' sees.

**Comment by epijim** [comment]
I'm assuming this might be common - e.g. I assume we'll often have depdencies on other internal packages, and not realise the issue as internally it points at a company RSPM that has packages not on CRAN.

**Comment by epijim** [comment]
Conversely - rather than doing it in the validation report which only runs on release - maybe it's good we proactively get those pre-commit hooks/or PR checks onto more packages? (like `admiral`). e.g. catch it before the validation is triggered. 

cc'ing @dgkf as an FYI.

**Comment by epijim** [comment]
Note my assumption `admiral.test` is the part where the validation template fails is the line it needs to install and run `R CMD Check` - and currently it's impossible to install admiral if your repo is CRAN due to the `admiral.test` `IMPORTS`.

**Comment by dinakar29** [comment]
Another thing to note - `admiral` uses an renv.lock file (which also contains `admiral.test`), so if thevalidatoR sees one of these files, it should `renv::restore()` instead of trying to install deps from elsewhere. This should be the default approach.
