### ISSUE TITLE
Validation Report with package name and version

### ISSUE THREAD

**Issue by bms63** [insightsengineering/thevalidatoR#54]
![image](https://user-images.githubusercontent.com/10111024/154764166-80e0defd-645f-41e1-a8a6-b65f4f8a8bca.png)

Is it possible to have the report have the package name and version number in it?  I was looking at the one for admiral and it just says validation-report.pdf.  Is it possible for it to be admiral-0_6_3-vaildation report.  

I'm just coming up to speed with the validation reports - so maybe there is something that could toggled to have it say what I would like.  I'm just imagining a see of these validation reports for all the pharmavers packages.  Want to make sure I'm looking at the right one and the right version.  

Also...the report is so cool to marvel at and look through.  Very nice!

**Comment by Crosita** [comment]
Thanks for the feedback @bms63! Great to know that 'pharmaverse' is looking at using our Validation Report template. FYI all Roche packages are validated internally using this template. 
@dgkf will be able to provide the latest updates on the report.

**Comment by dinakar29** [comment]
@bms63, I'm working with @thomas-neitmann to improve the UX of the report that is added to `admiral`, I'll consider this as an add-on to the UX. Cheers!

**Comment by dinakar29** [comment]
@bms63 - it looks like this worked exactly as intended for v0.7.1 for `admiral`. Thanks for the feedback on this btw.
